const teacher = (name, subject, email) => ({
  name: name,
  subject: subject,
  email: email,
  events: {
    "1AI": "",
    "1BI": "",
    "1CI": "",
    "1AM": "",
    "1BM": "",
    "1CM": "",
    "1AE": "",
    "1BE": "",
    "2AI": "",
    "2BI": "",
    "2CI": "",
    "2AM": "",
    "2BM": "",
    "2CM": "",
    "2AE": "",
    "2BE": "",
    "3AI": "",
    "3BI": "",
    "3CI": "",
    "3AM": "",
    "3BM": "",
    "3CM": "",
    "3AE": "",
    "3BE": "",
  },
});

export default teacher;
